### ISSUE TITLE
ModuleNotFoundError: no module named 'nm_utils'

### ISSUE THREAD

**Issue by natalier11** [predictive-clinical-neuroscience/braincharts#1]
Hi there!

I've been trying to set up the PCNToolkit and use the braincharts walkthrough for my lab and but I'm running into a small issue. I've set up an environment for the pcntoolkit and was able to successfully install it, however I'm getting an error when trying to run the following cell on the walkthrough:
import os
import numpy as np
import pandas as pd
import pickle
from matplotlib import pyplot as plt
import seaborn as sns

from pcntoolkit.normative import estimate, predict, evaluate
from pcntoolkit.util.utils import compute_MSLL, create_design_matrix
from nm_utils import calibration_descriptives, remove_bad_subjects, load_2d

I'm running this cell in a jupyter notebook with the appropriate pcn environment and am receiving the following error:
![20210819 JN nm_utils error](https://user-images.githubusercontent.com/73397911/130127525-0958a7b0-70f4-42c8-b47d-445f93fef4b0.png)
I've tried editing my environment and adding the nm_utils module but I receive the following install errors:
![20210819 HPC nm_utils install errors](https://user-images.githubusercontent.com/73397911/130127632-450953a5-032d-44f7-be34-6bdf1d7d2f15.png)
I was wondering if this module/dependency is available somewhere or if there's a different dependency I can use in it's place. Please let me know, thank you!

Natalie Remiszewski
nrem@uab.edu

**Comment by amarquand** [comment]
Hi - this is because you are not importing the nm_utils.py module correctly (basically python can't find that file)

The functions in nm_utils are not part of the standard toolbox, they are stored in a file in this distribution. So if you import them from that directory (or add it to the path) it should work.
