### ISSUE TITLE
Problem in apply_normative_models.ipynb with colab 

### ISSUE THREAD

**Issue by hanbing-gao** [predictive-clinical-neuroscience/braincharts#3]
Hi,

I tried to run the apply_normative_models.ipynb with colab, when I run this part:

`from pcntoolkit.normative import estimate, predict, evaluate`

I got:

> RuntimeError:
> Could not import 'mkl'. If you are using conda, update the numpy
> packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
> your environment for MKL 2018.
> 
> If you have MKL 2017 install and are not in a conda environment you
> can set the Theano flag blas.check_openmp to False. Be warned that if
> you set this flag and don't set the appropriate environment or make
> sure you have the right version you will get wrong results.

which was still working days before. Not sure if this happens because there might have been some updates in Colab.
I tried to install mkl again for different versions but did not work.

**Comment by amarquand** [comment]
Hi - is this still a problem?

**Comment by hanbing-gao** [comment]
> Hi - is this still a problem?

Hi prof. Marquand,
I haven't tried it with Colab after that. I built it locally. 
I checked it just right now and it looks fine. No problem for now. 
Thank you very much for such a good toolkit!
Best regards,
Hanbing

**Comment by amarquand** [comment]
You're welcome! And thanks for the feedback. I will close this issue now.
