### ISSUE TITLE
Missing L_insula from phenotypes_sa_dk_lh.txt

### ISSUE THREAD

**Issue by cooperr11** [predictive-clinical-neuroscience/braincharts#5]
Hi there,
the L_insula is missing from docs/phenotypes_sa_dk_lh.txt
Looks like it's been added to docs/phenotypes_ct_dk_lh.txt though.
Thanks!

**Comment by amarquand** [comment]
Hi - thanks for pointing this out. We will address this

**Comment by amarquand** [comment]
Sorry or the delay - this has been added now.
